language: ruby
cache: bundler
sudo: false
rvm: 2.5

install:
  - gem install bundler
  - bundle install

env:
  - JEKYLL_ENV=production

script:
  - bundle exec jekyll build

after_script:
  - bundle exec htmlproofer _site --http-status-ignore 999

after_success:
  - touch ./_site/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  on:
    branch: development
  github-token: $GITHUB_TOKEN
  local-dir: _site
  keep-history: true
  committer-from-gh: true
  target_branch: master
