title: Hiberbee | Tech Consulting for IT professionals
description: "Технический консалтинг и супервайзинг для разработчиков, техлидов, проектных команд. Специализации: DevOps, System Architecture, Engineering Practices, Software Engineering, Quality Assurance, technologies, services"
keywords: DevOps, System design, Engineering practices, Software engineering, Quality assurance, Technology, Services
email: vlad@hiberbee.com
baseurl: ""
url: "https://hiberbee.com"
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-pwa-plugin
author:
  name: "Vladyslav Volkov"
  email: "vlad@hiberbee.com"
  github: hiberbee
  facebook: hiberbee
  linkedin: vladyslavvolkov
  instagram: hiberbee
  telegram: nezquiraj
organization:
  name: Hiberbee
  address: Часопис\nL'va Tolstoho vulytsya\, 3\, Kiev\, Kiev\, Ukraine
google_analytics: UA-111095351-4
facebook_pixel: 402031503981717
facebook_app_id: 145510372820525
google_tag: GTM-P5LNHBZ
timezone: Europe/Kiev
exclude:
  - .bundle/*
  - Gemfile
  - Gemfile.lock
  - vendor/*
  - .sass-cache/*
  - build.gradle
push_app_id: d3180b47-35fb-477f-98a4-49105f4c3bb3
markdown: kramdown
collections:
  events:
    output: true
    permalink: /events/:title/:month-:day.ics
  trainings:
    output: true
    output_tags: true
    output_categories: true
    permalink: /trainings/:title/
  pages:
    output: true
    permalink: /:title/
defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
      sitemap: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "blank"
  - scope:
      path: ""
      type: "trainings"
    values:
      layout: "training"
pagination:
  enabled: true
  per_page: 100
autopages:
  enabled: true
  collections:
    enabled: true
    layouts:
      - 'category.html'
    title: 'Все тренинги'
    permalink: '/:coll'
  categories:
    enabled: true
    layouts:
      - 'category.html'
    title: 'Тренинги в категории &laquo;:cat&raquo;'
    permalink: '/category/:cat'
  tags:
    enabled: true
    layouts:
      - 'category.html'
    title: 'Тренинги с тегом &laquo;:tag&raquo;'
    permalink: '/tag/:tag'
future: true
pwa:
  dest_js_directory: assets/js
  precache_glob_ignores:
    - sw-register.js
  precache_glob_patterns:
    - "/assets/{js,css,img,fonts}/**/*.{js,woff,ttf,css,png,svg,jpg,jpeg}"
    - "/manifest.json"
    - "/favicon*.png"
    - "/index.html"
    - "/404.html"
    - "/faq/index.html"
    - "/privacy-policy/index.html"
    - "/taxonomy/index.html"
    - "/terms-of-use/index.html"
sass:
  style: compressed
webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/img/"]
  regenerate: false
  webp_path: nil
  exclude: []
