title: Hiberbee | Tech Consulting for IT professionals
description: "Технический консалтинг и супервайзинг для разработчиков, техлидов, проектных команд. Специализации: DevOps, System Architecture, Engineering Practices, Software Engineering, Quality Assurance, technologies, services"
email: vlad@hiberbee.com
baseurl: ""
url: "https://hiberbee.com"
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-pwa-plugin
  - jekyll-archives
author:
  name: "Vladyslav Volkov"
  email: "vlad@hiberbee.com"
  github: hiberbee
  facebook: hiberbee
  linkedin: vladyslavvolkov
  telegram: nezquiraj
organization:
  name: Hiberbee
  address: 3 Lva Tolstoho Str., "Chasopys" 1st floor, Kyiv, 01004
google_analytics: UA-111095351-4
facebook_pixel: 402031503981717
facebook_app_id: 145510372820525
google_tag: GTM-P5LNHBZ
feed:
  path: atom.xml
  categories:
    - dev-ops
    - system-design
    - engineering-practices
    - software-engineering
    - quality-assurance
    - technologies-services
timezone: Europe/Kiev
include:
  - 404.html
  - manifest.json
  - CNAME
  - service-worker.js
  - vcard.vcf
exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - vendor
  - build.gradle
push_app_id: d3180b47-35fb-477f-98a4-49105f4c3bb3
markdown: kramdown
permalink: /:month/:day/:title/
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
future: true
pwa:
  dest_js_directory: assets/js
  precache_glob_ignores:
    - sw-register.js
  precache_glob_patterns:
    - "/assets/{js,css,img,fonts}/**/*.{js,woff,ttf,css,png,svg,jpg,jpeg}"
    - "/index.html"
    - "/manifest.json"
    - "/404.html"
    - "/privacy-policy.html"
    - "/faq.html"
    - "/taxonomy.html"
    - "/terms-of-use.html"
    - "/favicon*.png"
sass:
  style: compressed
webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/img/"]
  regenerate: false
  webp_path: nil
  exclude: []
trainings_identity_map:
  do-000: docker-technology-intro
  do-001: docker-swarm-complete-cluster-infrastructure
  do-010: ansible-technology-intro
  do-020: kubernetes-technology-intro
  do-021: kubernetes-initial-setup-and-configuration
  do-022: kubernetes-configuring-running-controllers-workloads
  do-023: kubernetes-network-service-mesh-istio
  do-024: kubernetes-logging-elk
  do-025: kubernetes-push-pull-monitoring
  do-026: kubernetes-persistence-storages-volumes
  do-027: kubernetes-security-key-management
  do-030: cloud-native-providers
  ep-000: sdlc-intro
  ep-001: sdlc-solutions
  ep-002: sdlc-artifacts
  ep-010: exteme-programming-intro
  ep-020: ci-cd-intro
  ep-021: ci-pipeline-setup
  ep-022: cd-pipeline-setup
  ep-030: ide-intellij
  ep-031: remote-workstation
  qa-000: qa-automation-essentials
  qa-010: bdd-spec
  qa-011: bdd-cucumber
  qa-012: bdd-rest-karate
  qa-020: infrastructure-integration-testing
  qa-030: qa-java-stream-lambdas
  qa-040: qa-scala-performance-stress-testing
  sd-000: system-achicture-role-overview
  sd-010: system-design-spec-uml
  sd-011: system-design-spec-4-1-views
  sd-020: reverse-enginering-microservices
  se-010: java-intro
  se-020: spring-hibernate-intro
  se-021: spring-boot
  se-022: spring-cloud-native
  se-030: gradle-intro
  se-031: gradle-united
  se-032: gradle-advanced
  se-033: gradle-kotlin-dsl
  se-041: php-threads
  se-042: php-app-servers
  ts-010: db-graph-neo4j-kickoff
  ts-020: graphql-essentials
  ts-021: graphql-advanced
  ts-030: media-streaming-transform
  ts-040: mq-rabbitmq
  ts-050: serverless-intro
