url: "https://hiberbee.com"
plugins:
  - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-polyglot
  - jekyll-pwa-plugin
  - jekyll-sitemap
  - jekyll-webp
timezone: Europe/Kiev
exclude:
  - .bundle/*
  - .jekyll-metadata
  - .travis.yml
  - build.gradle
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor/*
markdown: CommonMark
languages: ["ru", "en"]
exclude_from_localization: ["assets"]
default_lang: ru
parallel_localization: true
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
collections:
  events:
    output: true
    permalink: "/events/:title/:month-:day.ics"
  trainings:
    output: true
    output_tags: true
    output_categories: true
    permalink: "/trainings/:title/"
  pages:
    output: true
    permalink: "/:title/"
defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
      sitemap: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "trainings"
    values:
      layout: "training"
pagination:
  enabled: true
  per_page: 100
autopages:
  enabled: true
  collections:
    enabled: true
    layouts:
      - "category.html"
    permalink: "/:coll"
  categories:
    enabled: true
    layouts:
      - "category.html"
    permalink: "/category/:cat"
  tags:
    enabled: true
    layouts:
      - "category.html"
    permalink: "/tag/:tag"
future: true
permalink: /blog/:title/
pwa:
  dest_js_directory: assets/js
  precache_glob_ignores:
    - sw-register.js
  precache_glob_patterns:
    - "/assets/{js,css,img,fonts}/**/*.{js,woff,webp,ttf,css,png,svg,jpg,jpeg}"
    - "/manifest.json"
    - "/*.png"
    - "/*.js"
    - "/**/*.html"
jekyll-minifier:
  exclude: 'feed.xml,manifest.json'
  uglifier_args:
    harmony: true
webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/img/"]
  regenerate: false
  webp_path: nil
  exclude: []
