do-000: "Docker: Technology overview & kick-off"
do-001: "Docker Swarm: Complete cluster infrastructure from scratch"
do-010: "Ansible: Configuration management & infrastructure provision"
do-020: "Kubernetes: Technology overview & kick-off for developers and DevOps"
do-021: "Kubernetes: Initial setup and configuration and local environment workflows"
do-022: "Kubernetes: Configuring and running controllers and workloads"
do-023: "Kubernetes: Network service mesh with Istio"
do-024: "Kubernetes: Logging with ELK stack"
do-025: "Kubernetes: Push and pull monitoring with Prometheus & TICK stacks"
do-026: "Kubernetes: Persistence, storages and volumes management with Ceph and S3"
do-027: "Kubernetes: Security and key management with Vault"
do-030: "Cloud Native providers"
ep-000: "SDLC: Introduction"
ep-001: "SDLC: Solutions"
ep-002: "SDLC: Artifacts"
ep-010: "Exteme Programming: Introduction"
ep-020: "Continuous integration & delivery: Introduction"
ep-021: "Continuous integration: Pipeline setup and configuration"
ep-022: "Continuous delivery: Pipeline setup and configuration"
ep-030: "Jetbrains IDE family: Killer features, complete configuration, ultimate tricks and incentive insights for all JetBrains users"
ep-031: "Thin client: Move your environment to the cloud"
qa-000: "QA Automation: Essentials"
qa-010: "BDD: Introduction"
qa-011: "BDD: Cucumber"
qa-012: "BDD: Testing REST/GraphQL API with Cucumber & Karate"
qa-020: "Infrastructure test automation: Spec-driven and integration testing for automation QA & software engineers"
qa-030: "Java 8 API: Streams API and functional interfaces with cutting-edge test frameworks for QA automation engineers"
qa-040: "Gatling: Performance and stress-testing with Scala/Gatling for automation QA engineers"
sd-000: "System Achicture: Role overview"
sd-010: "System design specification: UML"
sd-011: "System design specification: 4+1 architecture views"
sd-020: "Microservices: Reverse-engineering, references & best practices"
se-010: "Java: SL class"
se-020: "Spring & Hibernate: SL class"
se-021: "Spring Boot: SL class"
se-022: "Spring Cloud: Cloud Native application example"
se-030: "Gradle: SL class"
se-031: "Gradle: United polyglot build system"
se-032: "Gradle: Advanced"
se-033: "Gradle: Kotlin DSL"
se-041: "PHP: Native threads"
se-042: "PHP: Event loop & application servers"
ts-010: "Neo4J: Introduction to graph databases with samples for SQL-experienced engineers"
ts-020: "GraphQL API: Essentials and starter guide for everyone experienced with REST"
ts-021: "GraphQL API: Advanced client/server features and insights for everyone experienced with REST"
ts-030: "Media processing: Video-on-Demand, transmux, images operations"
ts-040: "Message queues: RabbitMQ"
ts-050: "Serverless: Fundamentals, frameworks, cloud providers"
tc-000: "Technical consulting: Free-style sessions"
