name: Deploy to Github Pages
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --production --ignore-scripts --prefer-offline
      - run: yarn deploy --user=${{ github.actor }}
